edition = "2021"
tab_spaces = 4
max_width = 80
reorder_imports = true
imports_granularity = "Crate"
format_code_in_doc_comments = true
# error_on_unformatted = false
group_imports = "StdExternalCrate"
