[package]
name = "amm_reflect"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "2.3.1"
solana-account-decoder = "2.3.1"
anyhow = "1"
rust_decimal = "1.36.0"
ahash = "0.8"
usdc-plus-exchange = "0.1.8"
solana-client = "2.3.1"
base64ct = "=1.7.3"
jupiter-amm-interface = "0.6.0"
