[package]
name = "amm_reflect"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "2.1.0"
solana-account-decoder = "2"
anyhow = "1"
serde_json = "1.0.114"
serde = "1.0.219"
rust_decimal = "1.36.0"
ahash = "0.8"
usdc-plus-exchange = "0.1.5"
